//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_CRUD_ENTITY.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmployeeId { get; set; }
        [Required(ErrorMessage ="This Field is Required")]
        public string EmployeeName { get; set; }
        //[DataType(DataType.MultilineText)]
        public string EmployeeAddress { get; set; }
        [Required(ErrorMessage = "This Field is Required")][EmailAddress(ErrorMessage = "Enter a valid email address")]
        public string EmployeeEmail { get; set; }
        [Phone(ErrorMessage = "Enter a valid Phone Number")]
        public string EmployeePhone { get; set; }
    }
}
